apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bdpq83o6r-python-gitops
  description: This is GitOps manifest for bdpq83o6r-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=bdpq83o6r-python
    backstage.io/kubernetes-id: bdpq83o6r-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bdpq83o6r-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bdpq83o6r-python
